# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for release
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Tarball
      run: tar czf cs2-agones.tar.gz bin/Release/net8.0/
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: cs2-agones.tar.gz
        generate_release_notes: true
        tag: ${{ inputs.tag }}